// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef VERILATED_VTESTHARNESS__SYMS_H_
#define VERILATED_VTESTHARNESS__SYMS_H_  // guard

#include "verilated.h"

// INCLUDE MODEL CLASS

#include "VTestHarness.h"

// INCLUDE MODULE CLASSES
#include "VTestHarness___024root.h"
#include "VTestHarness___024unit.h"

// DPI TYPES for DPI Export callbacks (Internal use)

// SYMS CLASS (contains all model state)
class VTestHarness__Syms final : public VerilatedSyms {
  public:
    // INTERNAL STATE
    VTestHarness* const __Vm_modelp;
    bool __Vm_didInit = false;

    // MODULE INSTANCE STATE
    VTestHarness___024root         TOP;
    VTestHarness___024unit         TOP____024unit;

    // SCOPE NAMES
    VerilatedScope __Vscope_TestHarness;
    VerilatedScope __Vscope_TestHarness__chiptop__system__bootROMDomainWrapper__bootrom__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__clint__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__dtm;
    VerilatedScope __Vscope_TestHarness__chiptop__system__dtm__dmiAccessChain;
    VerilatedScope __Vscope_TestHarness__chiptop__system__dtm__dtmInfoChain;
    VerilatedScope __Vscope_TestHarness__chiptop__system__dtm__tapIO_idcodeChain;
    VerilatedScope __Vscope_TestHarness__chiptop__system__plicDomainWrapper__plic;
    VerilatedScope __Vscope_TestHarness__chiptop__system__plicDomainWrapper__plic__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__prci_ctrl_domain__tileClockGater__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__prci_ctrl_domain__tileResetSetter__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__atomics;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__atomics__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__buffer__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__coupler_to_bootrom__fragmenter;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__coupler_to_bootrom__fragmenter__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__coupler_to_clint__fragmenter;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__coupler_to_clint__fragmenter__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__coupler_to_debug__fragmenter;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__coupler_to_debug__fragmenter__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__coupler_to_l2_ctrl__buffer__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__coupler_to_l2_ctrl__fragmenter;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__coupler_to_l2_ctrl__fragmenter__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__coupler_to_plic__fragmenter;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__coupler_to_plic__fragmenter__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__coupler_to_slave_named_clockgater__buffer__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__coupler_to_slave_named_clockgater__fragmenter;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__coupler_to_slave_named_clockgater__fragmenter__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__coupler_to_slave_named_tileresetsetter__buffer__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__coupler_to_slave_named_tileresetsetter__fragmenter;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__coupler_to_slave_named_tileresetsetter__fragmenter__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__fixer__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__in_xbar;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__in_xbar__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__in_xbar__monitor_1;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__out_xbar;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__out_xbar__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__wrapped_error_device__buffer__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_cbus__wrapped_error_device__error__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_fbus__buffer__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_fbus__coupler_from_port_named_serial_tl_ctrl__buffer__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__InclusiveCache_inner_TLBuffer__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__binder__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__cork;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__cork__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__cork__pool;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__abc_mshrs_0;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__abc_mshrs_1;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__abc_mshrs_2;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__abc_mshrs_3;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__abc_mshrs_4;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__abc_mshrs_5;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__abc_mshrs_6;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__abc_mshrs_7;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__abc_mshrs_8;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__abc_mshrs_9;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__bc_mshr;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__c_mshr;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__directory;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__requests;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__sinkA__putbuffer;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__sinkC;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__sinkC__putbuffer;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__sinkD;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__sourceB;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__sourceC;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__mods_0__sourceD;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_l2_wrapper__l2__monitor_1;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_mbus__coupler_to_memory_controller_port_named_axi4__axi4yank;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_mbus__coupler_to_memory_controller_port_named_axi4__tl2axi4;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_mbus__coupler_to_memory_controller_port_named_axi4__tl2axi4__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_mbus__coupler_to_port_named_serial_tl_mem__shrinker__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_mbus__fixer__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_mbus__picker__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_mbus__picker__monitor_1;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_mbus__subsystem_mbus_xbar;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_mbus__subsystem_mbus_xbar__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_pbus__atomics;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_pbus__atomics__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_pbus__buffer_1__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_pbus__buffer__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_pbus__coupler_to_device_named_uart_0__fragmenter;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_pbus__coupler_to_device_named_uart_0__fragmenter__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_pbus__coupler_to_slave_named_bootaddressreg__fragmenter;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_pbus__coupler_to_slave_named_bootaddressreg__fragmenter__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_pbus__fixer__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_pbus__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_pbus__out_xbar;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_pbus__out_xbar__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_sbus__coupler_from_bus_named_subsystem_fbus__widget__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_sbus__coupler_to_bus_named_subsystem_cbus__widget__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_sbus__fixer__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_sbus__fixer__monitor_1;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_sbus__system_bus_xbar;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_sbus__system_bus_xbar__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__subsystem_sbus__system_bus_xbar__monitor_1;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__buffer_1__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__alu_exe_unit;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__alu_exe_unit_1;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__alu_exe_unit_1__alu;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__alu_exe_unit__alu;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__csr;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__csr_exe_unit__alu;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_0;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_1;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_10;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_11;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_12;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_13;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_14;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_15;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_16;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_17;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_18;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_19;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_2;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_20;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_21;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_22;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_23;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_24;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_25;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_26;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_27;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_28;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_29;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_3;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_30;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_31;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_4;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_5;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_6;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_7;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_8;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_9;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fpiu_unit;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fpiu_unit__fdivsqrt;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fregfile;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_rename_stage;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_rename_stage__freelist;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_rename_stage__maptable;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_0;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_1;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_10;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_11;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_12;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_13;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_14;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_15;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_16;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_17;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_18;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_19;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_2;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_20;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_21;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_22;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_23;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_24;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_25;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_26;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_27;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_28;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_29;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_3;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_30;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_31;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_32;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_33;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_34;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_35;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_36;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_37;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_38;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_39;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_4;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_5;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_6;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_7;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_8;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_9;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__iregfile;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__jmp_unit;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__jmp_unit__ifpu;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_0;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_1;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_10;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_11;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_12;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_13;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_14;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_15;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_16;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_17;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_18;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_19;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_2;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_20;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_21;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_22;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_23;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_3;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_4;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_5;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_6;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_7;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_8;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_9;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_units_0__maddrcalc;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_units_1__maddrcalc;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__rename_stage;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__rename_stage__freelist;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__rename_stage__maptable;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__rob;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__dcache;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__dcache__mshrs;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__dcache__mshrs__mmios_0;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__dcache__mshrs__mshrs_0;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__dcache__mshrs__mshrs_1;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__dcache__mshrs__mshrs_2;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__dcache__mshrs__mshrs_3;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__dcache__mshrs__mshrs_4;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__dcache__mshrs__mshrs_5;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__dcache__mshrs__mshrs_6;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__dcache__mshrs__mshrs_7;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__frontend;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__frontend__bpd;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__frontend__icache;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__frontend__tlb;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__lsu;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__lsu__dtlb;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__ptw;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__tlMasterXbar;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__tlMasterXbar__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__tlMasterXbar__monitor_1;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tlDM__dmInner__dmInner;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tlDM__dmInner__dmInner__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tlDM__dmInner__dmInner__monitor_1;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tlDM__dmOuter__asource__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tlDM__dmOuter__dmOuter__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tlDM__dmOuter__dmiBypass__bar__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tlDM__dmOuter__dmiBypass__error;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tlDM__dmOuter__dmiBypass__error__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tlDM__dmOuter__dmiXbar;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tlDM__dmOuter__dmiXbar__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tsi_domain__buffer__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__tsi_domain__serdesser__monitor;
    VerilatedScope __Vscope_TestHarness__chiptop__system__uartClockDomainWrapper__uart_0__monitor;
    VerilatedScope __Vscope_TestHarness__ram__adapter;
    VerilatedScope __Vscope_TestHarness__ram__buffer_1__monitor;
    VerilatedScope __Vscope_TestHarness__ram__buffer__monitor;
    VerilatedScope __Vscope_TestHarness__ram__fragmenter;
    VerilatedScope __Vscope_TestHarness__ram__fragmenter_1;
    VerilatedScope __Vscope_TestHarness__ram__fragmenter_1__monitor;
    VerilatedScope __Vscope_TestHarness__ram__fragmenter__monitor;
    VerilatedScope __Vscope_TestHarness__ram__rom__monitor;
    VerilatedScope __Vscope_TestHarness__ram__serdesser__monitor;
    VerilatedScope __Vscope_TestHarness__ram__srams__monitor;
    VerilatedScope __Vscope_TestHarness__ram__xbar;
    VerilatedScope __Vscope_TestHarness__ram__xbar__monitor;

    // SCOPE HIERARCHY
    VerilatedHierarchy __Vhier;

    // CONSTRUCTORS
    VTestHarness__Syms(VerilatedContext* contextp, const char* namep, VTestHarness* modelp);
    ~VTestHarness__Syms();
    void VTestHarness__Syms_2();
    void VTestHarness__Syms_1();

    // METHODS
    const char* name() { return TOP.name(); }
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

#endif  // guard
